<a href="https://colab.research.google.com/github/Pritishcoder07/Movie_Recommendation/blob/main/Movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [353]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [354]:
df= pd.read_csv('netflix_titles_nov_2019.csv.zip')

In [355]:
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show

In [356]:
# show_id
# title
# director
# cast
# duration
# type
movie = df[['show_id','title','director','cast','duration','type','description','listed_in']]

In [357]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   show_id      5837 non-null   int64
 1   title        5837 non-null   object
 2   director     3936 non-null   object
 3   cast         5281 non-null   object
 4   duration     5837 non-null   object
 5   type         5837 non-null   object
 6   description  5837 non-null   object
 7   listed_in    5837 non-null   object
dtypes: int64(1), object(7)
memory usage: 364.9+ KB

In [358]:
movie.isnull().sum()

show_id           0
title             0
director       1901
cast            556
duration          0
type              0
description       0
listed_in         0
dtype: int64

In [359]:
movie.dropna(inplace=True)

In [360]:
movie.head()

,show_id,title,director,cast,duration,type,description,listed_in
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,67 min,Movie,"From Sierra de las Minas to Esquipulas, explor...","Documentaries, International Movies"
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",135 min,Movie,A goofy copywriter unwittingly convinces the I...,"Comedies, Dramas, International Movies"
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...",106 min,Movie,"Arranged to marry a rich man, young Ada is cru...","Dramas, Independent Movies, International Movies"
5,81172754,Crazy people,Moses Inwang,"Ramsey Nouah, Chigul, Sola Sobowale, Ireti Doy...",107 min,Movie,Nollywood star Ramsey Nouah learns that someon...,"Comedies, International Movies, Thrillers"
6,81120982,I Lost My Body,Jérémy Clapin,"Hakim Faris, Victoire Du Bois, Patrick d'Assum...",81 min,Movie,"Romance, mystery and adventure intertwine as a...","Dramas, Independent Movies, International Movies"

In [361]:
movie.shape

(3588, 8)

In [362]:
def remove_internal_spaces_from_names(names_string):
    if not isinstance(names_string, str) or not names_string.strip():
        return ""
    individual_names = [name.strip() for name in names_string.split(',')]

    processed_names = [name.replace(' ', '') for name in individual_names]

    return ','.join(processed_names)

movie['director'] = movie['director'].apply(remove_internal_spaces_from_names)

In [363]:
movie.head()

,show_id,title,director,cast,duration,type,description,listed_in
1,81197050,Guatemala: Heart of the Mayan World,"LuisAra,IgnacioJaunsolo",Christian Morales,67 min,Movie,"From Sierra de las Minas to Esquipulas, explor...","Documentaries, International Movies"
2,81213894,The Zoya Factor,AbhishekSharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",135 min,Movie,A goofy copywriter unwittingly convinces the I...,"Comedies, Dramas, International Movies"
3,81082007,Atlantics,MatiDiop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...",106 min,Movie,"Arranged to marry a rich man, young Ada is cru...","Dramas, Independent Movies, International Movies"
5,81172754,Crazy people,MosesInwang,"Ramsey Nouah, Chigul, Sola Sobowale, Ireti Doy...",107 min,Movie,Nollywood star Ramsey Nouah learns that someon...,"Comedies, International Movies, Thrillers"
6,81120982,I Lost My Body,JérémyClapin,"Hakim Faris, Victoire Du Bois, Patrick d'Assum...",81 min,Movie,"Romance, mystery and adventure intertwine as a...","Dramas, Independent Movies, International Movies"

In [364]:
movie['cast'] = movie['cast'].apply(remove_internal_spaces_from_names)

In [365]:
movie.head()

,show_id,title,director,cast,duration,type,description,listed_in
1,81197050,Guatemala: Heart of the Mayan World,"LuisAra,IgnacioJaunsolo",ChristianMorales,67 min,Movie,"From Sierra de las Minas to Esquipulas, explor...","Documentaries, International Movies"
2,81213894,The Zoya Factor,AbhishekSharma,"SonamKapoor,DulquerSalmaan,SanjayKapoor,Sikand...",135 min,Movie,A goofy copywriter unwittingly convinces the I...,"Comedies, Dramas, International Movies"
3,81082007,Atlantics,MatiDiop,"MamaSane,AmadouMbow,IbrahimaTraore,NicoleSougo...",106 min,Movie,"Arranged to marry a rich man, young Ada is cru...","Dramas, Independent Movies, International Movies"
5,81172754,Crazy people,MosesInwang,"RamseyNouah,Chigul,SolaSobowale,IretiDoyle,Ben...",107 min,Movie,Nollywood star Ramsey Nouah learns that someon...,"Comedies, International Movies, Thrillers"
6,81120982,I Lost My Body,JérémyClapin,"HakimFaris,VictoireDuBois,Patrickd'Assumçao,De...",81 min,Movie,"Romance, mystery and adventure intertwine as a...","Dramas, Independent Movies, International Movies"

In [366]:
movie['tags'] =  movie['description'] + movie['listed_in'] + movie['director'] + movie['cast']  + movie['duration']

In [367]:
movie.head()

,show_id,title,director,cast,duration,type,description,listed_in,tags
1,81197050,Guatemala: Heart of the Mayan World,"LuisAra,IgnacioJaunsolo",ChristianMorales,67 min,Movie,"From Sierra de las Minas to Esquipulas, explor...","Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor..."
2,81213894,The Zoya Factor,AbhishekSharma,"SonamKapoor,DulquerSalmaan,SanjayKapoor,Sikand...",135 min,Movie,A goofy copywriter unwittingly convinces the I...,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...
3,81082007,Atlantics,MatiDiop,"MamaSane,AmadouMbow,IbrahimaTraore,NicoleSougo...",106 min,Movie,"Arranged to marry a rich man, young Ada is cru...","Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru..."
5,81172754,Crazy people,MosesInwang,"RamseyNouah,Chigul,SolaSobowale,IretiDoyle,Ben...",107 min,Movie,Nollywood star Ramsey Nouah learns that someon...,"Comedies, International Movies, Thrillers",Nollywood star Ramsey Nouah learns that someon...
6,81120982,I Lost My Body,JérémyClapin,"HakimFaris,VictoireDuBois,Patrickd'Assumçao,De...",81 min,Movie,"Romance, mystery and adventure intertwine as a...","Dramas, Independent Movies, International Movies","Romance, mystery and adventure intertwine as a..."

In [368]:
nmovie = movie[['show_id','title','tags']]

In [369]:
nmovie

,show_id,title,tags
1,81197050,Guatemala: Heart of the Mayan World,"From Sierra de las Minas to Esquipulas, explor..."
2,81213894,The Zoya Factor,A goofy copywriter unwittingly convinces the I...
3,81082007,Atlantics,"Arranged to marry a rich man, young Ada is cru..."
5,81172754,Crazy people,Nollywood star Ramsey Nouah learns that someon...
6,81120982,I Lost My Body,"Romance, mystery and adventure intertwine as a..."
...,...,...,...
5831,70154110,Even the Rain,While making a film about the incursion of Chr...
5832,70141644,Mad Ron's Prevues from Hell,"This collection cherry-picks trailers, forgott..."
5833,70127998,Splatter,"After committing suicide, a washed-up rocker r..."
5834,70084180,Just Another Love Story,When he causes a car accident that leaves a yo...
5836,70053412,To and From New York,"While covering a story in New York City, a Sea..."

In [370]:
nmovie['tags'] = nmovie['tags'].apply(lambda x:x.lower())

In [371]:
nmovie.head()

,show_id,title,tags
1,81197050,Guatemala: Heart of the Mayan World,"from sierra de las minas to esquipulas, explor..."
2,81213894,The Zoya Factor,a goofy copywriter unwittingly convinces the i...
3,81082007,Atlantics,"arranged to marry a rich man, young ada is cru..."
5,81172754,Crazy people,nollywood star ramsey nouah learns that someon...
6,81120982,I Lost My Body,"romance, mystery and adventure intertwine as a..."

In [372]:
nmovie.shape

(3588, 3)

In [373]:
import nltk

In [374]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [375]:
def stem (text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [388]:
nmovie['tags'] = nmovie['tags'].apply(stem)

In [389]:
vector = cv.fit_transform(nmovie['tags']).toarray()

In [390]:
similarity = cosine_similarity(vector)

In [391]:
recommend('Atlantics')

Recommendations for 'Atlantics':
  - Ready to Mingle (Similarity: 0.3608)
  - The Promise (Similarity: 0.3608)
  - Caida del Cielo (Similarity: 0.3482)
  - Bewildered Bolbol (Similarity: 0.3333)
  - Hantu Kak Limah (Similarity: 0.3333)

In [376]:
nmovie['tags'] = nmovie['tags'].apply(stem)

In [377]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=4000,stop_words='english')

In [378]:
vector =cv.fit_transform(nmovie['tags']).toarray()

In [379]:
cv.get_feature_names_out()

array(['000', '10', '11', ..., 'zoëkravitz', 'álvarocervantes',
       'özgeborak'], dtype=object)

In [380]:
ps.stem('singing')

'sing'

In [381]:
nmovie.head().tags

1    from sierra de la mina to esquipulas, explor g...
2    a goofi copywrit unwittingli convinc the india...
3    arrang to marri a rich man, young ada is crush...
5    nollywood star ramsey nouah learn that someon ...
6    romance, mysteri and adventur intertwin as a y...
Name: tags, dtype: object

In [382]:
from sklearn.metrics.pairwise import cosine_similarity

In [383]:
similarity = cosine_similarity(vector)

In [384]:
similarity

array([[1.        , 0.15569979, 0.13159034, ..., 0.08703883, 0.15075567,
        0.07537784],
       [0.15569979, 1.        , 0.16903085, ..., 0.0745356 , 0.19364917,
        0.12909944],
       [0.13159034, 0.16903085, 1.        , ..., 0.06299408, 0.27277236,
        0.27277236],
       ...,
       [0.08703883, 0.0745356 , 0.06299408, ..., 1.        , 0.07216878,
        0.07216878],
       [0.15075567, 0.19364917, 0.27277236, ..., 0.07216878, 1.        ,
        0.125     ],
       [0.07537784, 0.12909944, 0.27277236, ..., 0.07216878, 0.125     ,
        1.        ]])

In [385]:
list(enumerate(similarity[3000]))

[(0, np.float64(0.1315903389919538)),
 (1, np.float64(0.1690308509457033)),
 (2, np.float64(0.23809523809523814)),
 (3, np.float64(0.18898223650461363)),
 (4, np.float64(0.28571428571428575)),
 (5, np.float64(0.1749635530559413)),
 (6, np.float64(0.12104550653376049)),
 (7, np.float64(0.23328473740792174)),
 (8, np.float64(0.15018785229652765)),
 (9, np.float64(0.2817180849095055)),
 (10, np.float64(0.14285714285714288)),
 (11, np.float64(0.11664236870396087)),
 (12, np.float64(0.04761904761904762)),
 (13, np.float64(0.15430334996209194)),
 (14, np.float64(0.10585122480499264)),
 (15, np.float64(0.1636634176769943)),
 (16, np.float64(0.04879500364742666)),
 (17, np.float64(0.11664236870396087)),
 (18, np.float64(0.04879500364742666)),
 (19, np.float64(0.20261022461827694)),
 (20, np.float64(0.060522753266880246)),
 (21, np.float64(0.15877683720748895)),
 (22, np.float64(0.1690308509457033)),
 (23, np.float64(0.1126872339638022)),
 (24, np.float64(0.05006261743217588)),
 (25, np.float64(0.04879500364742666)),
 (26, np.float64(0.0545544725589981)),
 (27, np.float64(0.24397501823713327)),
 (28, np.float64(0.10585122480499264)),
 (29, np.float64(0.0563436169819011)),
 (30, np.float64(0.0657951694959769)),
 (31, np.float64(0.14285714285714288)),
 (32, np.float64(0.3499271061118826)),
 (33, np.float64(0.09523809523809525)),
 (34, np.float64(0.060522753266880246)),
 (35, np.float64(0.13801311186847084)),
 (36, np.float64(0.1636634176769943)),
 (37, np.float64(0.21170244960998527)),
 (38, np.float64(0.10585122480499264)),
 (39, np.float64(0.2057377999494559)),
 (40, np.float64(0.11664236870396087)),
 (41, np.float64(0.0545544725589981)),
 (42, np.float64(0.11664236870396087)),
 (43, np.float64(0.14638501094227996)),
 (44, np.float64(0.09759000729485331)),
 (45, np.float64(0.18898223650461363)),
 (46, np.float64(0.1690308509457033)),
 (47, np.float64(0.3185110286353031)),
 (48, np.float64(0.20025046972870353)),
 (49, np.float64(0.1091089451179962)),
 (50, np.float64(0.06900655593423542)),
 (51, np.float64(0.10012523486435176)),
 (52, np.float64(0.10585122480499264)),
 (53, np.float64(0.058321184351980436)),
 (54, np.float64(0.1126872339638022)),
 (55, np.float64(0.13093073414159545)),
 (56, np.float64(0.10585122480499264)),
 (57, np.float64(0.09523809523809525)),
 (58, np.float64(0.11664236870396087)),
 (59, np.float64(0.27914526311954124)),
 (60, np.float64(0.051434449987363975)),
 (61, np.float64(0.2727723627949905)),
 (62, np.float64(0.10286889997472795)),
 (63, np.float64(0.13650472655798704)),
 (64, np.float64(0.06299407883487121)),
 (65, np.float64(0.18609684207969415)),
 (66, np.float64(0.12598815766974242)),
 (67, np.float64(0.15430334996209194)),
 (68, np.float64(0.15877683720748895)),
 (69, np.float64(0.10585122480499264)),
 (70, np.float64(0.1690308509457033)),
 (71, np.float64(0.12598815766974242)),
 (72, np.float64(0.2182178902359924)),
 (73, np.float64(0.19518001458970663)),
 (74, np.float64(0.0563436169819011)),
 (75, np.float64(0.10585122480499264)),
 (76, np.float64(0.06299407883487121)),
 (77, np.float64(0.1126872339638022)),
 (78, np.float64(0.21821789023599242)),
 (79, np.float64(0.15430334996209194)),
 (80, np.float64(0.058321184351980436)),
 (81, np.float64(0.14638501094227996)),
 (82, np.float64(0.23809523809523814)),
 (83, np.float64(0.10012523486435176)),
 (84, np.float64(0.10286889997472795)),
 (85, np.float64(0.09759000729485331)),
 (86, np.float64(0.26462806201248157)),
 (87, np.float64(0.1636634176769943)),
 (88, np.float64(0.11664236870396087)),
 (89, np.float64(0.15018785229652765)),
 (90, np.float64(0.11664236870396087)),
 (91, np.float64(0.11664236870396087)),
 (92, np.float64(0.2182178902359924)),
 (93, np.float64(0.2727723627949905)),
 (94, np.float64(0.23328473740792174)),
 (95, np.float64(0.15430334996209194)),
 (96, np.float64(0.058321184351980436)),
 (97, np.float64(0.09304842103984708)),
 (98, np.float64(0.20025046972870353)),
 (99, np.float64(0.21170244960998527)),
 (100, np.float64(0.06299407883487121)),
 (101, np.float64(0.2916059217599022)),
 (102, np.float64(0.10286889997472795)),
 (103, np.float64(0.1636634176769943)),
 (104, np.float64(0.09759000729485331)),
 (105, np.float64(0.060522753266880246)),
 (106, np.float64(0.10585122480499264)),
 (107, np.float64(0.15430334996209194)),
 (108, np.float64(0.1091089451179962)),
 (109, np.float64(0.0563436169819011)),
 (110, np.float64(0.11664236870396087)),
 (111, np.float64(0.06299407883487121)),
 (112, np.float64(0.12598815766974242)),
 (113, np.float64(0.1126872339638022)),
 (114, np.float64(0.0563436169819011)),
 (115, np.float64(0.08728715609439697)),
 (116, np.float64(0.1091089451179962)),
 (117, np.float64(0.15018785229652765)),
 (118, np.float64(0.058321184351980436)),
 (119, np.float64(0.15018785229652765)),
 (120, np.float64(0.1749635530559413)),
 (121, np.float64(0.12598815766974242)),
 (122, np.float64(0.10585122480499264)),
 (123, np.float64(0.06900655593423542)),
 (124, np.float64(0.06299407883487121)),
 (125, np.float64(0.1126872339638022)),
 (126, np.float64(0.20025046972870353)),
 (127, np.float64(0.25717224993681986)),
 (128, np.float64(0.14638501094227996)),
 (129, np.float64(0.058321184351980436)),
 (130, np.float64(0.09523809523809525)),
 (131, np.float64(0.2727723627949905)),
 (132, np.float64(0.051434449987363975)),
 (133, np.float64(0.1690308509457033)),
 (134, np.float64(0.14638501094227996)),
 (135, np.float64(0.08728715609439697)),
 (136, np.float64(0.09759000729485331)),
 (137, np.float64(0.1315903389919538)),
 (138, np.float64(0.12598815766974242)),
 (139, np.float64(0.11664236870396087)),
 (140, np.float64(0.16798421022632323)),
 (141, np.float64(0.15430334996209194)),
 (142, np.float64(0.1126872339638022)),
 (143, np.float64(0.1315903389919538)),
 (144, np.float64(0.19518001458970663)),
 (145, np.float64(0.15430334996209194)),
 (146, np.float64(0.1126872339638022)),
 (147, np.float64(0.16798421022632323)),
 (148, np.float64(0.10012523486435176)),
 (149, np.float64(0.24209101306752098)),
 (150, np.float64(0.04550157551932901)),
 (151, np.float64(0.10286889997472795)),
 (152, np.float64(0.24397501823713327)),
 (153, np.float64(0.1690308509457033)),
 (154, np.float64(0.06900655593423542)),
 (155, np.float64(0.0)),
 (156, np.float64(0.05006261743217588)),
 (157, np.float64(0.10012523486435176)),
 (158, np.float64(0.11664236870396087)),
 (159, np.float64(0.060522753266880246)),
 (160, np.float64(0.13650472655798704)),
 (161, np.float64(0.15877683720748895)),
 (162, np.float64(0.10286889997472795)),
 (163, np.float64(0.26462806201248157)),
 (164, np.float64(0.14285714285714288)),
 (165, np.float64(0.23328473740792174)),
 (166, np.float64(0.05292561240249632)),
 (167, np.float64(0.14638501094227996)),
 (168, np.float64(0.10012523486435176)),
 (169, np.float64(0.21170244960998527)),
 (170, np.float64(0.10585122480499264)),
 (171, np.float64(0.04879500364742666)),
 (172, np.float64(0.0563436169819011)),
 (173, np.float64(0.05292561240249632)),
 (174, np.float64(0.1636634176769943)),
 (175, np.float64(0.10012523486435176)),
 (176, np.float64(0.1126872339638022)),
 (177, np.float64(0.1091089451179962)),
 (178, np.float64(0.12598815766974242)),
 (179, np.float64(0.05292561240249632)),
 (180, np.float64(0.06900655593423542)),
 (181, np.float64(0.0545544725589981)),
 (182, np.float64(0.051434449987363975)),
 (183, np.float64(0.2182178902359924)),
 (184, np.float64(0.04761904761904762)),
 (185, np.float64(0.04761904761904762)),
 (186, np.float64(0.044543540318737404)),
 (187, np.float64(0.18898223650461363)),
 (188, np.float64(0.060522753266880246)),
 (189, np.float64(0.0545544725589981)),
 (190, np.float64(0.06900655593423542)),
 (191, np.float64(0.0563436169819011)),
 (192, np.float64(0.15877683720748895)),
 (193, np.float64(0.0545544725589981)),
 (194, np.float64(0.12598815766974242)),
 (195, np.float64(0.07715167498104596)),
 (196, np.float64(0.07484811885651196)),
 (197, np.float64(0.2057377999494559)),
 (198, np.float64(0.1091089451179962)),
 (199, np.float64(0.14285714285714288)),
 (200, np.float64(0.18609684207969415)),
 (201, np.float64(0.26462806201248157)),
 (202, np.float64(0.10012523486435176)),
 (203, np.float64(0.24209101306752098)),
 (204, np.float64(0.1283881477532739)),
 (205, np.float64(0.21398024625545647)),
 (206, np.float64(0.2057377999494559)),
 (207, np.float64(0.26462806201248157)),
 (208, np.float64(0.060522753266880246)),
 (209, np.float64(0.15018785229652765)),
 (210, np.float64(0.13957263155977062)),
 (211, np.float64(0.07715167498104596)),
 (212, np.float64(0.13957263155977062)),
 (213, np.float64(0.2439750182371333)),
 (214, np.float64(0.1690308509457033)),
 (215, np.float64(0.0545544725589981)),
 (216, np.float64(0.21170244960998527)),
 (217, np.float64(0.1126872339638022)),
 (218, np.float64(0.2727723627949905)),
 (219, np.float64(0.11664236870396087)),
 (220, np.float64(0.08728715609439697)),
 (221, np.float64(0.15430334996209194)),
 (222, np.float64(0.2253744679276044)),
 (223, np.float64(0.20619652471058064)),
 (224, np.float64(0.21170244960998527)),
 (225, np.float64(0.10286889997472795)),
 (226, np.float64(0.1690308509457033)),
 (227, np.float64(0.1636634176769943)),
 (228, np.float64(0.1636634176769943)),
 (229, np.float64(0.25717224993681986)),
 (230, np.float64(0.1636634176769943)),
 (231, np.float64(0.0563436169819011)),
 (232, np.float64(0.21170244960998527)),
 (233, np.float64(0.1749635530559413)),
 (234, np.float64(0.23328473740792174)),
 (235, np.float64(0.2182178902359924)),
 (236, np.float64(0.058321184351980436)),
 (237, np.float64(0.0545544725589981)),
 (238, np.float64(0.051434449987363975)),
 (239, np.float64(0.04199605255658081)),
 (240, np.float64(0.1126872339638022)),
 (241, np.float64(0.26462806201248157)),
 (242, np.float64(0.0563436169819011)),
 (243, np.float64(0.18156825980064073)),
 (244, np.float64(0.20025046972870353)),
 (245, np.float64(0.1749635530559413)),
 (246, np.float64(0.18156825980064073)),
 (247, np.float64(0.1749635530559413)),
 (248, np.float64(0.2253744679276044)),
 (249, np.float64(0.15430334996209194)),
 (250, np.float64(0.2057377999494559)),
 (251, np.float64(0.1126872339638022)),
 (252, np.float64(0.09759000729485331)),
 (253, np.float64(0.10286889997472795)),
 (254, np.float64(0.2253744679276044)),
 (255, np.float64(0.2057377999494559)),
 (256, np.float64(0.3175536744149779)),
 (257, np.float64(0.21170244960998527)),
 (258, np.float64(0.11664236870396087)),
 (259, np.float64(0.11664236870396087)),
 (260, np.float64(0.05292561240249632)),
 (261, np.float64(0.1690308509457033)),
 (262, np.float64(0.18898223650461363)),
 (263, np.float64(0.0545544725589981)),
 (264, np.float64(0.11664236870396087)),
 (265, np.float64(0.060522753266880246)),
 (266, np.float64(0.05006261743217588)),
 (267, np.float64(0.0545544725589981)),
 (268, np.float64(0.1126872339638022)),
 (269, np.float64(0.12104550653376049)),
 (270, np.float64(0.04652421051992354)),
 (271, np.float64(0.051434449987363975)),
 (272, np.float64(0.03688555567816587)),
 (273, np.float64(0.13957263155977062)),
 (274, np.float64(0.058321184351980436)),
 (275, np.float64(0.10585122480499264)),
 (276, np.float64(0.1749635530559413)),
 (277, np.float64(0.058321184351980436)),
 (278, np.float64(0.2182178902359924)),
 (279, np.float64(0.09759000729485331)),
 (280, np.float64(0.04550157551932901)),
 (281, np.float64(0.09759000729485331)),
 (282, np.float64(0.12104550653376049)),
 (283, np.float64(0.24209101306752098)),
 (284, np.float64(0.0545544725589981)),
 (285, np.float64(0.36004114991154784)),
 (286, np.float64(0.1126872339638022)),
 (287, np.float64(0.2182178902359924)),
 (288, np.float64(0.13650472655798704)),
 (289, np.float64(0.07273929674533079)),
 (290, np.float64(0.04879500364742666)),
 (291, np.float64(0.09304842103984708)),
 (292, np.float64(0.1336306209562122)),
 (293, np.float64(0.10286889997472795)),
 (294, np.float64(0.222717701593687)),
 (295, np.float64(0.10286889997472795)),
 (296, np.float64(0.04761904761904762)),
 (297, np.float64(0.2057377999494559)),
 (298, np.float64(0.10585122480499264)),
 (299, np.float64(0.20025046972870353)),
 (300, np.float64(0.041239304942116126)),
 (301, np.float64(0.10286889997472795)),
 (302, np.float64(0.10012523486435176)),
 (303, np.float64(0.18609684207969415)),
 (304, np.float64(0.1126872339638022)),
 (305, np.float64(0.1690308509457033)),
 (306, np.float64(0.20025046972870353)),
 (307, np.float64(0.10286889997472795)),
 (308, np.float64(0.1091089451179962)),
 (309, np.float64(0.2817180849095055)),
 (310, np.float64(0.1091089451179962)),
 (311, np.float64(0.19518001458970663)),
 (312, np.float64(0.3273268353539886)),
 (313, np.float64(0.2503130871608794)),
 (314, np.float64(0.19518001458970663)),
 (315, np.float64(0.1904761904761905)),
 (316, np.float64(0.04879500364742666)),
 (317, np.float64(0.10585122480499264)),
 (318, np.float64(0.30550504633038933)),
 (319, np.float64(0.18156825980064073)),
 (320, np.float64(0.21170244960998527)),
 (321, np.float64(0.0)),
 (322, np.float64(0.058321184351980436)),
 (323, np.float64(0.2182178902359924)),
 (324, np.float64(0.18898223650461363)),
 (325, np.float64(0.11664236870396087)),
 (326, np.float64(0.10286889997472795)),
 (327, np.float64(0.2182178902359924)),
 (328, np.float64(0.17118419700436519)),
 (329, np.float64(0.18156825980064073)),
 (330, np.float64(0.1091089451179962)),
 (331, np.float64(0.13093073414159545)),
 (332, np.float64(0.13093073414159545)),
 (333, np.float64(0.05292561240249632)),
 (334, np.float64(0.11664236870396087)),
 (335, np.float64(0.11664236870396087)),
 (336, np.float64(0.2886751345948129)),
 (337, np.float64(0.1690308509457033)),
 (338, np.float64(0.23262105259961768)),
 (339, np.float64(0.1690308509457033)),
 (340, np.float64(0.1126872339638022)),
 (341, np.float64(0.15877683720748895)),
 (342, np.float64(0.14285714285714288)),
 (343, np.float64(0.1126872339638022)),
 (344, np.float64(0.07597371763975865)),
 (345, np.float64(0.2503130871608794)),
 (346, np.float64(0.042796049251091296)),
 (347, np.float64(0.1636634176769943)),
 (348, np.float64(0.2730094531159741)),
 (349, np.float64(0.11664236870396087)),
 (350, np.float64(0.20025046972870353)),
 (351, np.float64(0.2057377999494559)),
 (352, np.float64(0.11664236870396087)),
 (353, np.float64(0.0545544725589981)),
 (354, np.float64(0.10012523486435176)),
 (355, np.float64(0.11664236870396087)),
 (356, np.float64(0.14638501094227996)),
 (357, np.float64(0.1690308509457033)),
 (358, np.float64(0.0657951694959769)),
 (359, np.float64(0.11664236870396087)),
 (360, np.float64(0.13093073414159545)),
 (361, np.float64(0.1126872339638022)),
 (362, np.float64(0.1126872339638022)),
 (363, np.float64(0.11664236870396087)),
 (364, np.float64(0.1649572197684645)),
 (365, np.float64(0.1636634176769943)),
 (366, np.float64(0.060522753266880246)),
 (367, np.float64(0.1636634176769943)),
 (368, np.float64(0.24397501823713327)),
 (369, np.float64(0.10286889997472795)),
 (370, np.float64(0.05292561240249632)),
 (371, np.float64(0.12156613477096617)),
 (372, np.float64(0.0563436169819011)),
 (373, np.float64(0.10585122480499264)),
 (374, np.float64(0.18898223650461363)),
 (375, np.float64(0.21170244960998527)),
 (376, np.float64(0.20025046972870353)),
 (377, np.float64(0.15018785229652765)),
 (378, np.float64(0.10012523486435176)),
 (379, np.float64(0.1636634176769943)),
 (380, np.float64(0.3003757045930553)),
 (381, np.float64(0.06900655593423542)),
 (382, np.float64(0.12598815766974242)),
 (383, np.float64(0.15018785229652765)),
 (384, np.float64(0.21170244960998527)),
 (385, np.float64(0.18156825980064073)),
 (386, np.float64(0.060522753266880246)),
 (387, np.float64(0.1636634176769943)),
 (388, np.float64(0.07273929674533079)),
 (389, np.float64(0.05292561240249632)),
 (390, np.float64(0.0545544725589981)),
 (391, np.float64(0.20025046972870353)),
 (392, np.float64(0.1283881477532739)),
 (393, np.float64(0.06299407883487121)),
 (394, np.float64(0.10012523486435176)),
 (395, np.float64(0.08728715609439697)),
 (396, np.float64(0.26462806201248157)),
 (397, np.float64(0.314970394174356)),
 (398, np.float64(0.18156825980064073)),
 (399, np.float64(0.1636634176769943)),
 (400, np.float64(0.051434449987363975)),
 (401, np.float64(0.19738550848793068)),
 (402, np.float64(0.18609684207969418)),
 (403, np.float64(0.18898223650461363)),
 (404, np.float64(0.04761904761904762)),
 (405, np.float64(0.21170244960998527)),
 (406, np.float64(0.2057377999494559)),
 (407, np.float64(0.18200630207731605)),
 (408, np.float64(0.29277002188455997)),
 (409, np.float64(0.10012523486435176)),
 (410, np.float64(0.060522753266880246)),
 (411, np.float64(0.11664236870396087)),
 (412, np.float64(0.14638501094227996)),
 (413, np.float64(0.1091089451179962)),
 (414, np.float64(0.1091089451179962)),
 (415, np.float64(0.11664236870396087)),
 (416, np.float64(0.15018785229652765)),
 (417, np.float64(0.0)),
 (418, np.float64(0.2253744679276044)),
 (419, np.float64(0.18200630207731605)),
 (420, np.float64(0.058321184351980436)),
 (421, np.float64(0.19738550848793068)),
 (422, np.float64(0.3175536744149779)),
 (423, np.float64(0.1126872339638022)),
 (424, np.float64(0.05292561240249632)),
 (425, np.float64(0.12104550653376049)),
 (426, np.float64(0.20025046972870353)),
 (427, np.float64(0.1091089451179962)),
 (428, np.float64(0.18609684207969415)),
 (429, np.float64(0.13957263155977062)),
 (430, np.float64(0.1636634176769943)),
 (431, np.float64(0.2916059217599022)),
 (432, np.float64(0.19518001458970663)),
 (433, np.float64(0.18200630207731605)),
 (434, np.float64(0.18200630207731605)),
 (435, np.float64(0.19518001458970663)),
 (436, np.float64(0.1690308509457033)),
 (437, np.float64(0.10012523486435176)),
 (438, np.float64(0.05292561240249632)),
 (439, np.float64(0.21170244960998527)),
 (440, np.float64(0.09100315103865803)),
 (441, np.float64(0.10585122480499264)),
 (442, np.float64(0.1126872339638022)),
 (443, np.float64(0.15018785229652765)),
 (444, np.float64(0.03798685881987932)),
 (445, np.float64(0.08908708063747481)),
 (446, np.float64(0.11664236870396087)),
 (447, np.float64(0.18156825980064073)),
 (448, np.float64(0.2182178902359924)),
 (449, np.float64(0.12598815766974242)),
 (450, np.float64(0.1126872339638022)),
 (451, np.float64(0.30261376633440124)),
 (452, np.float64(0.17817416127494962)),
 (453, np.float64(0.0)),
 (454, np.float64(0.060522753266880246)),
 (455, np.float64(0.10585122480499264)),
 (456, np.float64(0.03742405942825598)),
 (457, np.float64(0.03217447260438935)),
 (458, np.float64(0.1636634176769943)),
 (459, np.float64(0.18156825980064073)),
 (460, np.float64(0.06900655593423542)),
 (461, np.float64(0.13801311186847084)),
 (462, np.float64(0.2182178902359924)),
 (463, np.float64(0.060522753266880246)),
 (464, np.float64(0.11664236870396087)),
 (465, np.float64(0.060522753266880246)),
 (466, np.float64(0.06900655593423542)),
 (467, np.float64(0.20025046972870353)),
 (468, np.float64(0.12104550653376049)),
 (469, np.float64(0.18156825980064073)),
 (470, np.float64(0.21170244960998527)),
 (471, np.float64(0.15018785229652765)),
 (472, np.float64(0.06299407883487121)),
 (473, np.float64(0.0)),
 (474, np.float64(0.060522753266880246)),
 (475, np.float64(0.1749635530559413)),
 (476, np.float64(0.15430334996209194)),
 (477, np.float64(0.21170244960998527)),
 (478, np.float64(0.060522753266880246)),
 (479, np.float64(0.058321184351980436)),
 (480, np.float64(0.16798421022632323)),
 (481, np.float64(0.19518001458970663)),
 (482, np.float64(0.2503130871608794)),
 (483, np.float64(0.15430334996209194)),
 (484, np.float64(0.1636634176769943)),
 (485, np.float64(0.1636634176769943)),
 (486, np.float64(0.05006261743217588)),
 (487, np.float64(0.19518001458970663)),
 (488, np.float64(0.3175536744149779)),
 (489, np.float64(0.2182178902359924)),
 (490, np.float64(0.051434449987363975)),
 (491, np.float64(0.08728715609439697)),
 (492, np.float64(0.09304842103984708)),
 (493, np.float64(0.13093073414159545)),
 (494, np.float64(0.09523809523809525)),

In [386]:
def recommend(movie_title):
    try:
        movie_index = nmovie[nmovie['title'] == movie_title].index[0]
    except IndexError:
        print(f"Movie '{movie_title}' not found in the dataset.")
        return

    distances = similarity[movie_index]
    # Get the top 5 most similar movies (excluding itself) and their distances
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    print(f"Recommendations for '{movie_title}':")
    for i in movies_list:
        print(f"  - {nmovie.iloc[i[0]].title} (Similarity: {i[1]:.4f})")

In [387]:
recommend('Atlantics')

Recommendations for 'Atlantics':
  - Ready to Mingle (Similarity: 0.3727)
  - Caida del Cielo (Similarity: 0.3651)
  - The Promise (Similarity: 0.3608)
  - Hantu Kak Limah (Similarity: 0.3333)
  - Lechmi (Similarity: 0.3333)