<a href="https://colab.research.google.com/github/Pritishcoder07/Movie_Recommendation/blob/main/Movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [5]:
df= pd.read_csv('netflix_titles_nov_2019.csv.zip')

In [6]:
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show

In [41]:
# show_id
# title
# director
# cast
# rating
# duration
# type
movie = df[['show_id','title','director','cast','duration','type']]

In [42]:
movie.head()

,show_id,title,director,cast,duration,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",1 Season,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,67 min,Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",135 min,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...",106 min,Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...",2 Seasons,TV Show

In [43]:
movie.shape

(5837, 6)

In [44]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   show_id   5837 non-null   int64
 1   title     5837 non-null   object
 2   director  3936 non-null   object
 3   cast      5281 non-null   object
 4   duration  5837 non-null   object
 5   type      5837 non-null   object
dtypes: int64(1), object(5)
memory usage: 273.7+ KB

In [45]:
movie.isnull().sum()

show_id        0
title          0
director    1901
cast         556
duration       0
type           0
dtype: int64

In [46]:
movie.duplicated().sum()

np.int64(0)

In [47]:
movie['director']=movie['director'].fillna('')

In [48]:
movie['cast']=movie['cast'].fillna(' ')

In [49]:
movie.dropna(inplace=True)

In [50]:
movie.iloc[0].cast

'Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang Bu-ja, Lee Jae-ryong, Min Jin-woong, Kim Won-hae, Yoo Teo'

In [51]:
movie['director']=movie['director'].apply(lambda x: x.split() if isinstance(x, str) else x)