<a href="https://colab.research.google.com/github/Pritishcoder07/Movie_Recommendation/blob/main/Movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('movies_dataset.csv.zip')

In [3]:
df.head()

,Unnamed: 0,User_Id,Movie_Name,Rating,Genre
0,0,1,Pulp Fiction (1994),5.0,Comedy|Crime|Drama|Thriller
1,1,1,Three Colors: Red (Trois couleurs: Rouge) (1994),3.5,Drama
2,2,1,Three Colors: Blue (Trois couleurs: Bleu) (1993),5.0,Drama
3,3,1,Underground (1995),5.0,Comedy|Drama|War
4,4,1,Singin' in the Rain (1952),3.5,Comedy|Musical|Romance

In [5]:
df.shape

(25000095, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000095 entries, 0 to 25000094
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   User_Id     int64
 2   Movie_Name  object
 3   Rating      float64
 4   Genre       object
dtypes: float64(1), int64(2), object(2)
memory usage: 953.7+ MB

In [8]:
df.isnull().sum()

Unnamed: 0    0
User_Id       0
Movie_Name    0
Rating        0
Genre         0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)